# Generated by Django 4.0.1 on 2022-02-01 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_perfil_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='foto',
            field=models.ImageField(blank=True, default='usuario-de-perfil.png', null=True, upload_to='fotos/perfil/%d/%m/%Y'),
        ),
    ]
