# Generated by Django 4.0.1 on 2022-02-04 14:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0004_perfil_seguidores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='seguidores',
            field=models.ManyToManyField(related_name='seguidores', to=settings.AUTH_USER_MODEL),
        ),
    ]
