# Generated by Django 4.0.1 on 2022-02-02 16:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_perfil_foto'),
        ('instagram', '0005_alter_comentario_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField(max_length=1000)),
                ('data', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinatario', to='usuarios.perfil')),
                ('emissario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emisario', to='usuarios.perfil')),
            ],
        ),
    ]
