# Generated by Django 4.0.1 on 2022-02-04 14:44

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('instagram', '0006_mensagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='postagem',
            name='data',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 4, 11, 44, 25, 598679)),
        ),
        migrations.AlterField(
            model_name='postagem',
            name='like',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
