# Generated by Django 4.0.1 on 2022-02-07 06:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0007_postagem_data_alter_postagem_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagem',
            name='emissario_nome',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='postagem',
            name='data',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 7, 3, 17, 12, 917022)),
        ),
    ]
