# Generated by Django 4.0.1 on 2022-02-08 17:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_perfil_seguidores'),
        ('instagram', '0008_mensagem_emissario_nome_alter_postagem_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postagem',
            name='data',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 8, 14, 12, 8, 922495)),
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.IntegerField()),
                ('data', models.DateTimeField(default=datetime.datetime(2022, 2, 8, 14, 12, 8, 926012))),
                ('usuario_viu', models.BooleanField(default=False)),
                ('de', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='de', to='usuarios.perfil')),
                ('para', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='para', to='usuarios.perfil')),
                ('postagem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postagem', to='instagram.postagem')),
            ],
        ),
    ]
